
import unittest
import pandas as pd
import numpy as np
from graphrag.index.workflows.create_final_text_units import create_final_text_units
from graphrag.index.operations.finalize_community_reports import finalize_community_reports
from graphrag.index.workflows.create_communities import create_communities
from graphrag.index.operations.finalize_entities import finalize_entities
from graphrag.index.operations.finalize_relationships import finalize_relationships
from graphrag.data_model.schemas import (
    TEXT_UNITS_FINAL_COLUMNS,
    COMMUNITY_REPORTS_FINAL_COLUMNS,
    COMMUNITIES_FINAL_COLUMNS,
    ENTITIES_FINAL_COLUMNS,
    RELATIONSHIPS_FINAL_COLUMNS
)

class TestBugFixes(unittest.TestCase):
    """Tests for recent bug fixes ensuring robustness against empty/missing data."""

    def test_create_final_text_units_missing_cols(self):
        """Test create_final_text_units with inputs that result in missing join columns."""
        # Minimal valid inputs that don't match each other, causing left joins to have NaNs
        text_units = pd.DataFrame({"id": ["tu1"], "text": ["text"], "n_tokens": [10], "document_ids": [["doc1"]]})
        # Empty entities and relationships to force failed joins
        final_entities = pd.DataFrame({"id": [], "text_unit_ids": []})
        final_relationships = pd.DataFrame({"id": [], "text_unit_ids": []})
        final_covariates = None

        # This previously failed with NameError: name 'np' is not defined
        output = create_final_text_units(text_units, final_entities, final_relationships, final_covariates)
        
        self.assertTrue(all(col in output.columns for col in TEXT_UNITS_FINAL_COLUMNS))
        # Verify list columns are actually lists, not NaNs
        self.assertIsInstance(output.iloc[0]["entity_ids"], (list, np.ndarray))
        self.assertEqual(len(output.iloc[0]["entity_ids"]), 0)

    def test_finalize_community_reports_missing_cols(self):
        """Test finalize_community_reports with reports missing standard columns."""
        # Reports missing most columns generated by LLM
        reports = pd.DataFrame({"community": [1]})
        communities = pd.DataFrame({
            "community": [1], "parent": [0], "children": [[]], "size": [5], "period": ["2024-01"]
        })

        # This previously failed with NameError if we used np without import, 
        # or KeyError if we didn't fill missing columns.
        output = finalize_community_reports(reports, communities)

        self.assertTrue(all(col in output.columns for col in COMMUNITY_REPORTS_FINAL_COLUMNS))
        self.assertEqual(output.iloc[0]["title"], "") # Default value check

    def test_create_communities_empty(self):
        """Test create_communities with empty inputs."""
        entities = pd.DataFrame(columns=["id", "title"])
        relationships = pd.DataFrame(columns=["source", "target", "weight"])
        
        # This previously could fail on .max() of empty series
        output = create_communities(entities, relationships, max_cluster_size=10, use_lcc=True)
        
        self.assertTrue(all(col in output.columns for col in COMMUNITIES_FINAL_COLUMNS))
        self.assertEqual(len(output), 0)

    def test_finalize_entities_missing_degree(self):
        """Test finalize_entities when degree calculation might fail or return nothing."""
        entities = pd.DataFrame({"id": ["e1"], "title": ["Entity1"], "type": ["person"], "description": ["desc"], "text_unit_ids": [["tu1"]]})
        # Empty relationships -> no graph -> potentially no degree info
        relationships = pd.DataFrame(columns=["source", "target", "weight"])
        
        output = finalize_entities(entities, relationships)
        
        self.assertTrue(all(col in output.columns for col in ENTITIES_FINAL_COLUMNS))
        self.assertIn("degree", output.columns)
        self.assertEqual(output.iloc[0]["degree"], 0)

    def test_finalize_relationships_missing_degree(self):
        """Test finalize_relationships when degree info is missing."""
        relationships = pd.DataFrame({"source": ["s1"], "target": ["t1"], "weight": [1.0], "description": ["desc"], "text_unit_ids": [["tu1"]]})
        
        # In a real scenario, compute_degree might fail to link up if node names don't match perfectly,
        # leading to missing 'combined_degree' if not handled carefully.
        # Here we just ensure it runs.
        output = finalize_relationships(relationships)
        
        self.assertTrue(all(col in output.columns for col in RELATIONSHIPS_FINAL_COLUMNS))
        self.assertIn("combined_degree", output.columns)

if __name__ == "__main__":
    unittest.main()
